### PR TITLE
Major update to the existing documentation

### PR DESCRIPTION
**Pull request by rafmudaf**
**Complete this sentence**
THIS PULL REQUEST **IS** READY TO MERGE.

**Feature or improvement description**
This pull request provides a major update to the online documentation in the form of general tidying and cleanup plus some restructuring of the layout and organization. All sections were modified except the user guide which will be updated in a subsequent pull request.

Installation
- The [Getting Started](https://openfast.readthedocs.io/en/dev/source/get_started.html) section was removed and incorporated into this section as it was mostly redundant
- A higher level structure was added
- The availability of precompiled binaries for Windows is made more explicit and clear
- The CygWin compile instructions have been removed **Lets discuss this in the comments**
- A deeper explanation of CMake is provided

Testing
This is all structurally the same, but the content has been cleaned up and improved. Better examples for running the regression test are given.

Developer Guide
- The Doxygen API reference is enabled (it was previously off)
- Subsections were cleaned up and content updated

Sections yet to be improved:
- [Adding Documentation](https://raf-openfast.readthedocs.io/en/docs-general_updates/source/dev/build_doc.html#adding-documentation)
- Compiling on Windows Linux Subsystem, CygWin, or MinGW in [installation appendix](https://raf-openfast.readthedocs.io/en/docs-general_updates/source/install/index.html#appendix)

**Related issue, if one exists**
None

**Impacted areas of the software**
Documentation

**Test results, if applicable**
A live version of these updates is available at: https://raf-openfast.readthedocs.io/en/docs-general_updates/

### CODE REVIEW

**Comment by rafmudaf** [comment]
@andrew-platt @ashesh2512 Could you take a look at the changes here and provide some feedback?

**Comment by rafmudaf** [comment]
Hearing no objections, I'm going to merge this pull request today.
@michaelasprague @jjonkman have you had a chance to look at it?
@bjonkman any further feedback?

**Comment by bjonkman** [comment]
@rafmudaf , I haven't had time to read much of this and probably won't have time any time soon. I don't have any objections to you merging it.

**Comment by andrew-platt** [comment]
I have no objections to merging it.

There are a few items related to BeamDyn that need updating. I will include those in the BeamDyn PR.

**Comment by rafmudaf** [comment]
Ok, sounds good. This pull request does not change the user documentation, but I have some other ones coming regarding that portion of the docs.

**Pull request merged**
