### PR TITLE
Migrate the HydroDyn Manual to readthedocs

### PR DESCRIPTION
**Pull request by rafmudaf**
**Feature or improvement description**
This pull request migrates the HydroDyn Manual from FAST 8 into the OpenFAST web-based documentation on readthedocs.
See it live at https://raf-openfast.readthedocs.io/en/docs-hydrodyn_manual/source/user/hydrodyn/index.html

**Related issue, if one exists**
#179 

**Impacted areas of the software**
HydroDyn documentation

### CODE REVIEW

**Comment by rafmudaf** [comment]
For reference: https://github.com/rafmudaf/openfast/pull/16

**Comment by rafmudaf** [comment]
I've migrated the remaining missing equations that I and @andrew-platt have found. I believe this pull request is now ready to go! @jjonkman @andrew-platt do either of you want to take another look?

https://raf-openfast.readthedocs.io/en/docs-hydrodyn_manual/source/user/hydrodyn/index.html

**Comment by jjonkman** [comment]
I would like to review this at some point and make any changes necessary based on the recent updates to HydroDyn in v2.6.  But I probably won't get to this for a couple weeks and I don't want to hold up the merge either, so, I'm happy if you want to merge it now and I'll review at a later point.

**Comment by rafmudaf** [comment]
@jjonkman That sounds good to me. At this point, this pull request is specific to migrating the documentation to readthedocs so we can have another one for updating the HydroDyn documentation to reflect the latest changes.

**Pull request merged**
