### PR TITLE
[BugFix] incorrect pitch/roll moments on tapered elements crossing water line

### PR DESCRIPTION
**Pull request by andrew-platt**
** This pull request is ready to be merged**

**Feature or improvement description**

There were two negative signs missing in the calculation of the centroid for tapered members crossing the still water line, and one incorrect variable name.  The negative signs were missing in the original implementation plan.

**Related issue, if one exists**
This had been reported by a collaborator on an ARPA-E ATLANTIS project.

**Impacted areas of the software**
HydroDyn module.  Only tapered members crossing the still water surface are affected

**Additional supporting information**

**Test results, if applicable**
Added a very simple test case of a tapered cylinder (0.1m taper over 40 m) with a prescribed pitch motion.

Original results showing pitching moment that was way too large:
hd_taper_HydroMyi--orig

Corrected results in this PR:
hd_taper_HydroMyi--corrected

### CODE REVIEW

**Comment by andrew-platt** [comment]
@mattEhall, take a look at the code change for updating the plan.  This now matches your python script (I can upload the pages of algebra if you want the proof).

Should we add some of that derivation into the docs at some point?

**Review by HaymanConsulting — APPROVED** [review]
Looks like in addition to the negative signs (which, as you state, did not appear in the implementation plan), there was an additional typo in the code, where the value of r1 was used instead of rh.  The implementation plan does, indeed, call out rh in that particular term.

I'll leave the verification of the final form of the equation to Matt H.

**Comment by mattEhall** [comment]
These corrections look good, Andy. They match what I have in a Python verification script and match the corrected derivation. The trends in the plot of corrected moments look right. Thanks for tracking the errors down!

**Review by jjonkman — APPROVED** [review]
Thanks for tracking down this bug!  This is one part of the implementation plan that I was not able to check in detail.

**Pull request merged**
