### PR TITLE
Cpp library gluecode

### PR DESCRIPTION
**Pull request by gantech**
This pull request adds a FAST - C++ interface and a sample driver program to illustrate the use of this class.  This mostly does not modify the existing code except for some additions to the InitOut data of Aerodyn and ElastoDyn modules.

### CODE REVIEW

**Comment by sayerhs** [comment]
@gantech Can you merge with `dev` and then resubmit? Right now there are conflicts with merge.

**Comment by gantech** [comment]
Ok. Will try. I think this is due to the fact that I forked off master initially and master being ahead of dev. This pull request merges cleanly with master.

**Comment by sayerhs** [comment]
`master` and `dev` were synced, so the only conflict is in the `beamdyn/CmakeLists.txt` should be a minor fix.

**Comment by sayerhs** [comment]
@gantech Did you fix CMake rules for `beamdynlib`? It seems to have broken some rules for export.

**Comment by gantech** [comment]
Thanks @sayerhs. This is odd. I only resolved the conflicts I saw on github. 

@michaelasprague Could I add to the documentation in another pull request. I'm focused on getting the capability to work with Nalu to run OWEZ soon.

Also.. I have a few more mods based on a discussion with Matt Churchfield yesterday. I'll get those in today as well. Then it should be ready to merge.

**Pull request merged**
