### PR TITLE
Added some comments to Morison

### PR DESCRIPTION
**Pull request by mattEhall**
**THIS PULL REQUEST IS READY TO MERGE**

Added some comments to Morison.f90 and made some notes (marked "mhall:") to follow up on.

### CODE REVIEW

**Comment by rafmudaf** [comment]
@jjonkman have you had a chance to review these comments or is there someone else who should?

**Comment by jjonkman** [comment]
I haven't, but my understanding is that @mattEhall is currently working with @ghaymanNREL on further commenting of the HydroDyn source code.

**Comment by rafmudaf** [comment]
Ok sounds good, thanks for the update

**Comment by rafmudaf** [comment]
Thanks @ghaymanNREL.

Ready to merge, @mattEhall @jjonkman?

**Comment by jjonkman** [comment]
I'm OK with these changes if @ghaymanNREL is.  @ghaymanNREL is currently working on other HydroDyn improvements, which will likely further change this source code and its documentation.

**Comment by rafmudaf** [comment]
Thanks!

**Pull request merged**
