### PR TITLE
Update of Unsteady Aero model UAMod=2, corrections and added parameters

### PR DESCRIPTION
**Pull request by alvarogonzalezsalcedo**
Some changes related to the correct implementation of the code DYSTOOL in the option UAMod=2 of FAST have been performed. Most of them here and there are corrections, but there are also changes related to the application of parameters similar to f in the classical BL theory to Cd and Cm apart from Cl. The value of those parameters is modified depending on the flow separation progress. A standard selection of values for each range is hard-coded, for a performance similar to the original code.

### CODE REVIEW

**Comment by alvarogonzalezsalcedo** [comment]
The `fprimeprime_m` variable is set in line 450 (`fprimeprime_m = 0` as a default value) and in line 705  (`fprimeprime_m   = fprime_m - Df_m` when `UAMod=2`) inside the subroutine `ComputeKelvinChange` (called by subroutine `UA_CalcOutput` in line 1649) of UnsteadyAero.f90. 

The value of `fprimeprime_m` in line 1758 is assured. Is that correct?

**Comment by bjonkman** [comment]
Thanks, @alvarogonzalezsalcedo. It looks like I somehow missed line 705 when I merged your code in my branch. 
 
I am attempting to merge your code into some other changes that NREL gave me last year based on Envision's review of the code, as well as some other changes that Envision made in the data types/formatting so that the code was easier to review. These changes are in a conflicting pull request, and I am attempting to resolve the differences. There are some conflicts that I would appreciate your input on.

We found that `xd%tau_V` was set to 0 at the start of the updateStates routine, but that should have happened at the end of the routine. This was updated here: https://github.com/bjonkman/openfast/commit/b65aac8765c92da72a693e54241b2d935bc1fa95. Your pull request also modified the logic around setting `xd%tau_V`. I would like to make sure this logic still makes sense. Here's what I came up with when I merged your code in: https://github.com/bjonkman/openfast/commit/78bc8182da49c9283618e30a63f15d1725388294#diff-8d31125126182649142afdfce4dcd436

The final merged code is on this branch: https://github.com/bjonkman/openfast/tree/b/Envision-UA.

Could you take a look at the final code and let me know what you think? I'm still testing it, but if you have any comments, I would appreciate it.

**Comment by alvarogonzalezsalcedo** [comment]
Thanks @bjonkman, and sorry for the delay. I was trying to review the whole final code, but I have realised it is better to answer first to the question about `xd%tau_V`. To put the condition of `xd%tau_V=0` at the end is correct (both options could work, the only difference is a delay of one time step between two vortex shedding processes) and the logic for `p%UAMod == UA_Gonzalez` makes sense in your code. In fact, I have noticed that I had an equivalent condition to restart the vortex shedding at the end of the UA_UpdateDiscOtherState routine (lines 1296 - 1299 in your code) which was probably annuling the condition I had put in the begining of the subrutine. The only difference in this condition is that instead of setting the value of `xd%tau_V` to 0, it saves the excess of `xd%tau_V` above `BL_p%T_VL + T_sh`. I hope this help.

**Comment by alvarogonzalezsalcedo** [comment]
Dear @bjonkman, I have not found major problems in the final merged code on the branch https://github.com/bjonkman/openfast/tree/b/Envision-UA. However, I have a few comments about possible errors or improvements.

1_ Line 45 (and others): If it is possible: Gonzales -> Gonzalez
2_ Lines 259, 263 and 267: I think this change could be reasonable: `Get_f_c_from_Lookup = 0.0_ReKi` -> `Get_f_c_from_Lookup = 1.44_ReKi`
3_ Line 537: I think this is an error to correct: `KC%Cc_pot = KC%Cn_alpha_q_circ * KC%alpha_e * u%alpha` -> `KC%Cc_pot = KC%C_nalpha_circ * KC%alpha_e*u%alpha`
4_ Line 606: I think this is an error to correct: `KC%fprime_m = (Cm_temp - Cd0_temp) / Cn_temp` -> `KC%fprime_m = (Cm_temp - Cm0) / Cn_temp`
5_ Line 636-637: Additional initialization can be included: `KC%fprimeprime_m = KC%fprimeprime`

I'm going to repeat the validation of the stand-alone UA model for different 2D airfoils with the merged code including these changes.

**Comment by rafmudaf** [comment]
@alvarogonzalezsalcedo @bjonkman does pull request #226 supersede this one?

**Comment by bjonkman** [comment]
Yes, all of these code changes (plus a few more) are included in #226.

**Comment by rafmudaf** [comment]
Ok, then I'll close this pull request and work on getting #226 approved and merged.

**Pull request closed without merging**
