### PR TITLE
Updated Turbsim files in the develop branch

### PR DESCRIPTION
**Pull request by lssraman**
Modified URef to UHub as was suggested by Bonnie.

### CODE REVIEW

**Comment by rafmudaf** [comment]
Moving @bjonkman's comment from pull request #103 to here:

For my two cents: If you're going to use a single wind speed in the Gen coherence model, I recommend using p%UHub instead of p%met%URef. URef could be defined at a height off the grid.

**Comment by rafmudaf** [comment]
@lssraman could you please remove these files from git:
- modules-local/turbsim/src/TSsubs.f90.bak
- modules-local/turbsim/src/TurbSim.f90.bak

Also, did you intend to remove modules-local/turbsim/src/BlankModVKM.f90? As is, your pull request does not compile TurbSim due to this missing dependency in TSsubs.f90.

**Comment by lssraman** [comment]
@rafmudaf , I have updated these . Could you please check if it compiles now?
Thank you.

**Comment by jjonkman** [comment]
@lssraman -- My understanding from @bjonkman is that she requested changes to this pull request through a pull request to your fork.  Can you address @bjonkman's changes and resubmit/update your pull request?

**Comment by rafmudaf** [comment]
@lssraman This pull request is on my radar and I do intend to merge it soon. However, I am currently working on adding regression tests for TurbSim and other modules within OpenFAST, so I'm hoping to use this pull request as a test run for the TurbSim regression tests. My apologies for the delay.

**Comment by jjonkman** [comment]
@rafmudaf -- Have you already added the TurbSim regression tests into the r-test?  My understanding is that this pull request will change the TurbSim test results, so, this should not have been merged until we understand the effect of this pull request on the results.

**Comment by rafmudaf** [comment]
Hello @jjonkman -- The TurbSim regression tests are not yet added to the testing framework. The code changes here are for debugging with the exception of a change to the mean wind speed definition which was corrected from the initial change by @bjonkman above.

Changing the mean wind speed definition will certainly change the response, but the comment [here](https://github.com/OpenFAST/openfast/pull/104#issuecomment-389254460) suggests that it is understood and desired. Pull request #171 is also likely to have changed the response so I can revert that one until the turbsim regression tests are in place. What do you think?

**Comment by jjonkman** [comment]
Hi @rafmudaf,

Pull request #171 fixed a bug that was never caught by existing tests (i.e. cases where the number of components in the user-specified time-series input file is less than 3), so, I'm OK with merging this change.

But pull request #104 will effect the test results and also impacts the documentation.  I would prefer it if the associated test and documentation changes are included in the pull request with the source code change (following the OpenFAST development philosophy).

I had sent an e-mail to you and @michaelasprague in June about older FAST v8 documentation and tests that are effected by open and recently merged OpenFAST pull requests.  Any progress on migrating these to OpenFAST so that the tests and documentation can be made consistent with the OpenFAST source code?

**Comment by rafmudaf** [comment]
Good point, associated tests and documentation changes should be included with a pull request. Moving forward with TurbSim, I've created [issue #176](https://github.com/OpenFAST/openfast/issues/176) which lists these required updates to the testing and documentation.

**Pull request merged**
