### PR TITLE
Fix for Visual Studio builds with ADI

### PR DESCRIPTION
**Pull request by bjonkman**
This pull request is ready to be merged.

**Feature or improvement description**
This PR updates the build process so that ADI's registry runs in the VS solution files. It also 
- removes a few extrap/interp routines that aren't used (and don't need to be generated).
- removes non-standard tabs from the Fortran source code
- removes some unused variables from AD.

**Impacted areas of the software**
Visual Studio builds with code that contains the ADI module.

**Test results, if applicable**
This does not change any results

### CODE REVIEW

**Review by andrew-platt — APPROVED** [review]

**Comment by ebranlard** [comment]
I suspected the parallelization of FWrap Init to be buggy. I've removed it and the tests seems to pass now...

**Comment by bjonkman** [comment]
Thanks, @ebranlard!

**Comment by bjonkman** [comment]
FWIW: when I pulled up the GitHub Action artifacts of the failing FAST.Farm case (before Emmanuel reverted that change in dev), the plots are unreadable:

image

I haven't spent any time trying to figure out what's going wrong there, but thought I'd draw it to someone's attention. 

The other PRs that I submitted about the same time also failed on the same case as this one, but they didn't produce any .html file. So, something strange is going on with that.

**Comment by ebranlard** [comment]
Yes, I've noticed this as well, I'm not quite sure what's going on. I ended up comparing the files in pyDatView instead.

**Comment by andrew-platt** [comment]
I'm able to reproduce this locally as well.  
Screen Shot 2022-11-09 at 5 32 52 PM

**Pull request merged**
