### PR TITLE
Add ElastoDyn blade-node rotational velocity and translational acceleration output

### PR DESCRIPTION
**Pull request by bjonkman**
**Complete this sentence**
THIS PULL REQUEST IS READY TO MERGE

**Feature or improvement description**
Added rotational velocity and translational acceleration to ElastoDyn blade-node output mesh (with help from @jjonkman)

**Related issue, if one exists**
Fixes https://github.com/OpenFAST/openfast/issues/39

**Impacted areas of the software**
This could have a small effect on models that use AeroDyn15 and ElastoDyn where the two models have nodes that are some distance apart.

### CODE REVIEW

**Comment by andrew-platt** [comment]
Is there an `OutListParameters.xlsx` for ElastoDyn somewhere?

**Comment by jjonkman** [comment]
As far as I understand, the OutListParameters.xlsx spreadsheet included in the FAST v8.16 archive is the most up-to-date version, but has not yet been migrated to the OpenFAST GitHub repo.  This spreadsheet contains tabs for both ElastoDyn and ServoDyn (and copies of the OutList for BeamDyn and AeroDyn v15).

**Comment by andrew-platt** [comment]
We've split migrated several to GitHub at this point and updated them to reflect recent changes (AeroDyn, AeroDyn14, BeamDyn, InflowWind, OrcaFlex Interface).  I think the rest are still in the openfast-library/src/ copy.  Could you update that one with the new ElastoDyn channels?

**Comment by bjonkman** [comment]
Please see this sheet for updated channels: https://github.com/bjonkman/openfast/blob/f/Linear/modules/openfast-library/src/OutListParameters.xlsx. I really want only one version of this spreadsheet with separate tabs for each module. It's super painful to have multiple spreadsheets with the same name.

HOWEVER, **this pull request doesn't add WriteOutput values**, it merely adds values to the mesh output so that the motions can be transferred correctly to other modules. No change to the spreadsheet is necessary.

**Comment by andrew-platt** [comment]
Perfect.  Thanks for the clarification.

**Pull request merged**
