### PR TITLE
parallel build with make

### PR DESCRIPTION
**Pull request by rafaelmudafort**
This pull request:
- Adds missing dependency information between modules in CMake which allows GNU Make to parallelize the build process.
- Updates the CMake installation documentation with parallel build info
- Renames all driver executables to include "_driver" in the name. Some module drivers were called by the module name like "aerodyn" for the AeroDyn15 module but other drivers like "beamdn_driver" include "_driver". Reading the targets list from `make help` left some ambiguity.
- Compiles turbsim as an executable rather than a library

```
rmudafor@~/Development/openfast/build: ctest -j 8
Test project /Users/rmudafor/Development/openfast/build
      Start  1: AWT_YFix_WSt
      Start  2: AWT_WSt_StartUp_HighSpShutDown
      Start  3: AWT_YFree_WSt
      Start  4: AWT_YFree_WTurb
      Start  5: AWT_WSt_StartUpShutDown
      Start  6: AOC_WSt
      Start  7: AOC_YFree_WTurb
      Start  8: AOC_YFix_WSt
 1/31 Test  #1: AWT_YFix_WSt .............................   Passed   44.55 sec
      Start  9: UAE_Dnwind_YRamp_WSt
 2/31 Test  #6: AOC_WSt ..................................   Passed   61.13 sec
      Start 10: UAE_Upwind_Rigid_WRamp_PwrCurve
 3/31 Test  #2: AWT_WSt_StartUp_HighSpShutDown ...........   Passed   77.40 sec
      Start 11: WP_VSP_WTurb_PitchFail
 4/31 Test  #3: AWT_YFree_WSt ............................   Passed   90.76 sec
      Start 12: WP_VSP_ECD
 5/31 Test  #8: AOC_YFix_WSt .............................   Passed   95.16 sec
      Start 13: WP_VSP_WTurb
 6/31 Test  #5: AWT_WSt_StartUpShutDown ..................   Passed  113.74 sec
      Start 14: WP_Stationary_Linear
 7/31 Test #14: WP_Stationary_Linear .....................   Passed    4.60 sec
      Start 15: SWRT_YFree_VS_EDG01
 8/31 Test #11: WP_VSP_WTurb_PitchFail ...................   Passed   67.33 sec
      Start 16: SWRT_YFree_VS_EDC01
 9/31 Test #12: WP_VSP_ECD ...............................   Passed   74.54 sec
      Start 17: SWRT_YFree_VS_WTurb
10/31 Test #10: UAE_Upwind_Rigid_WRamp_PwrCurve ..........   Passed  157.04 sec
      Start 18: 5MW_Land_DLL_WTurb
11/31 Test  #9: UAE_Dnwind_YRamp_WSt .....................   Passed  248.79 sec
      Start 19: 5MW_OC3Mnpl_DLL_WTurb_WavesIrr
12/31 Test  #4: AWT_YFree_WTurb ..........................   Passed  309.09 sec
      Start 20: 5MW_OC3Trpd_DLL_WSt_WavesReg
13/31 Test #13: WP_VSP_WTurb .............................   Passed  214.54 sec
      Start 21: 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth
14/31 Test  #7: AOC_YFree_WTurb ..........................   Passed  356.03 sec
      Start 22: 5MW_ITIBarge_DLL_WTurb_WavesIrr
15/31 Test #22: 5MW_ITIBarge_DLL_WTurb_WavesIrr ..........   Passed  168.69 sec
      Start 23: 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti
16/31 Test #16: SWRT_YFree_VS_EDC01 ......................   Passed  387.70 sec
      Start 24: 5MW_OC3Spar_DLL_WTurb_WavesIrr
17/31 Test #18: 5MW_Land_DLL_WTurb .......................   Passed  417.46 sec
      Start 25: 5MW_OC4Semi_WSt_WavesWN
18/31 Test #15: SWRT_YFree_VS_EDG01 ......................   Passed  631.09 sec
      Start 26: 5MW_Land_BD_DLL_WTurb
19/31 Test #24: 5MW_OC3Spar_DLL_WTurb_WavesIrr ...........   Passed  271.95 sec
      Start 27: static_cantilever_beam
20/31 Test #27: static_cantilever_beam ...................   Passed    2.26 sec
      Start 28: isotropic_rollup
21/31 Test #23: 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti ....   Passed  283.49 sec
      Start 29: curved_beam
22/31 Test #28: isotropic_rollup .........................   Passed    2.73 sec
      Start 30: 5MW_dynamic
23/31 Test #29: curved_beam ..............................   Passed    1.82 sec
      Start 31: beamdyn_utest
24/31 Test #31: beamdyn_utest ............................   Passed    0.77 sec
25/31 Test #30: 5MW_dynamic ..............................   Passed  123.95 sec
26/31 Test #25: 5MW_OC4Semi_WSt_WavesWN ..................   Passed  519.29 sec
27/31 Test #19: 5MW_OC3Mnpl_DLL_WTurb_WavesIrr ...........   Passed  908.10 sec
28/31 Test #17: SWRT_YFree_VS_WTurb ......................   Passed  1127.80 sec
29/31 Test #26: 5MW_Land_BD_DLL_WTurb ....................   Passed  934.22 sec
30/31 Test #20: 5MW_OC3Trpd_DLL_WSt_WavesReg .............   Passed  1903.11 sec
31/31 Test #21: 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth ...   Passed  3282.54 sec

100% tests passed, 0 tests failed out of 31

Label Time Summary:
aerodyn14    = 2027.37 sec (7 tests)
aerodyn15    = 10722.78 sec (19 tests)
beamdyn      = 1064.98 sec (5 tests)
dynamic      = 123.95 sec (1 test)
elastodyn    = 11815.92 sec (25 tests)
hydrodyn     = 7337.16 sec (7 tests)
map          = 724.13 sec (3 tests)
moordyn      = 519.29 sec (1 test)
openfast     = 12750.15 sec (26 tests)
servodyn     = 12745.55 sec (25 tests)
static       =   6.81 sec (3 tests)
subdyn       = 6093.74 sec (3 tests)

Total Test time (real) = 3592.91 sec
```

### CODE REVIEW

**Comment by rafaelmudafort** [comment]
@sayerhs the updates I'd like your feedback on here are
- changing the module driver names to include "_driver" ... good idea / bad idea? 
- I added dependencies in cmake config, a second look from you would be great

**Comment by sayerhs** [comment]
@rafaelmudafort 

- I don't have a strong opinion one way or other regarding `_driver` for module drivers. The reason `aerodyn` was not `aerodyn_driver` in my initial CMake work was because I was trying to be match with the original `aerodyn` executable shipped by NREL. I tacked on `_driver` for some utilities later because I had already used the non-driver names for the libraries. If I was doing it today, I'd make all executables just the name of the module and use `module_lib` as targets for the libraries. This makes for an awkward filename: `libaerodyn_lib.a`, but chances are users will rarely need to deal with it directly. 

- Can you point me to the commit/changes where you introduced _dependencies_ in CMake config? I am not seeing it in the diffs from this pull request.

**Comment by rafaelmudafort** [comment]
@sayerhs, thanks for the info.

I added dependencies with `target_link_libraries` in 
- https://github.com/OpenFAST/openfast/pull/57/commits/ff296adca8a8a376d20c6c5dc5aee01d074ca667
- https://github.com/OpenFAST/openfast/pull/57/commits/93097668d57370861a166d45058f773343d04839

**Comment by sayerhs** [comment]
Ah. I try to provide those in order usually, i.e., `ifwlib` also links to `nwtclibs` so I prefer to do 

`target_link_libraries(aerodynlib ifwlib nwtclibs)`

but not sure if that matters much in this case.

**Comment by rafaelmudafort** [comment]
Ok, good catch. I'll update that for clarity.

Possibly the link is still working since the dependencies are [transitive](https://cmake.org/cmake/help/v3.3/command/target_link_libraries.html#libraries-for-both-a-target-and-its-dependents) and nwtclibs comes into AD14 with ifwlib. Or maybe the order isn't sensitive.

**Pull request merged**
