### PR TITLE
Consolidate directories and update tools

### PR DESCRIPTION
**Pull request by rafmudaf**
**Complete this sentence**
THIS PULL REQUEST IS READY TO MERGE

**Feature or improvement description**
1. Consolidates the `modules-local/` and `modules-ext/` directories into one `modules/`
2. Adds the unsteady aero driver target to cmake
3. Moves the lone directory until `utilities/` into `share/`
4. Disables the intel travis ci branch as we don't have a paid license and the travis support for intel is limited

**Related issue, if one exists**
None

**Impacted areas of the software**
Module directory structure, cmake, regression test scripts, `.travis.yml`

**Additional supporting information**
This has been suggested to me a few times by various people and I don't see a reason to not do this. If there's a historic or otherwise relevant reason to maintain the current directory structure, please comment here.

**Test results, if applicable**
This pull request only changes the infrastructure around the code, not the content of the code itself. Rather than running the full regression test suite, I've run the linearized cases, beamdyn module tests, and the unit tests to demonstrate that all of that infrastructure is up to date.
```
(/home/rmudafor/.conda-envs/openfast) peregrine.n2471@~/openfast/build: ctest -L linear && ctest -j4 -R bd_ && ctest -R beamdyn_utest
Test project /home/rmudafor/openfast/build
    Start 26: WP_Stationary_Linear
1/4 Test #26: WP_Stationary_Linear .............   Passed    0.49 sec
    Start 27: Ideal_Beam_Fixed_Free_Linear
2/4 Test #27: Ideal_Beam_Fixed_Free_Linear .....   Passed    1.16 sec
    Start 28: Ideal_Beam_Free_Free_Linear
3/4 Test #28: Ideal_Beam_Free_Free_Linear ......   Passed    1.19 sec
    Start 29: 5MW_Land_BD_Linear
4/4 Test #29: 5MW_Land_BD_Linear ...............   Passed   38.41 sec

100% tests passed, 0 tests failed out of 4

Label Time Summary:
aerodyn15    =   0.49 sec (1 test)
beamdyn      =  40.75 sec (3 tests)
elastodyn    =   0.49 sec (1 test)
linear       =  41.25 sec (4 tests)
openfast     =  41.25 sec (4 tests)
servodyn     =  38.41 sec (1 test)

Total Test time (real) =  41.26 sec
Test project /home/rmudafor/openfast/build
    Start 30: bd_5MW_dynamic
    Start 31: bd_5MW_dynamic_gravity_Az00
    Start 32: bd_5MW_dynamic_gravity_Az90
    Start 34: bd_isotropic_rollup
1/7 Test #34: bd_isotropic_rollup ..............   Passed    1.80 sec
    Start 36: bd_static_twisted_with_k1
2/7 Test #36: bd_static_twisted_with_k1 ........   Passed    0.40 sec
    Start 33: bd_curved_beam
3/7 Test #33: bd_curved_beam ...................   Passed    0.80 sec
    Start 35: bd_static_cantilever_beam
4/7 Test #35: bd_static_cantilever_beam ........   Passed    0.40 sec
5/7 Test #32: bd_5MW_dynamic_gravity_Az90 ......   Passed    5.09 sec
6/7 Test #31: bd_5MW_dynamic_gravity_Az00 ......   Passed    5.09 sec
7/7 Test #30: bd_5MW_dynamic ...................   Passed   24.82 sec

100% tests passed, 0 tests failed out of 7

Label Time Summary:
beamdyn    =  38.42 sec (7 tests)
dynamic    =  35.01 sec (3 tests)
static     =   3.41 sec (4 tests)

Total Test time (real) =  24.84 sec
Test project /home/rmudafor/openfast/build
    Start 37: beamdyn_utest
1/1 Test #37: beamdyn_utest ....................   Passed    0.01 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   0.02 sec
```

### CODE REVIEW

**Comment by andrew-platt** [comment]
This looks like a good idea to me!  There isn't much reason to have two different modules directories anymore.

**Comment by bjonkman** [comment]
Thanks, @rafmudaf. I think it is much less confusing to have only one modules directory.

Could you also replace all of the references to `modules-local` and `modules-ext` in the path names contained in the `vs-build/*.v*proj` (text) files? Otherwise all of the Visual Studio builds will be broken.

**Comment by rafmudaf** [comment]
Thanks for pointing that out, @bjonkman, its updated. My IDE for some reason didn't search the `vs-build` directory so I missed that. An automated test for Windows sure would be nice. NREL may be installing gitlab on our servers soon so that could be an easy path forward.

**Comment by bjonkman** [comment]
Can I suggest a minor change in wording in the README files you are adding? Instead of 
`This legacy version of this module`, could you use `The legacy version...` or `A legacy version...` or even `Legacy versions...` ? Otherwise it sounds like the OpenFAST repository contains legacy code.

**Comment by rafmudaf** [comment]
Good catch, yes I'll make that change. Thanks for the feedback!

**Comment by rafmudaf** [comment]
@michaelasprague Per your suggestion, I've now included a readme in every module. You can view these by navigating through the modules at https://github.com/rafmudaf/openfast/tree/feature/directory_cleanup/modules.

**Pull request merged**
