### PR TITLE
ElastoDyn: add YawBrTV[xyz]p output channels

### PR DESCRIPTION
**Pull request by aitorplaza**
This pull request is ready to be merged.

**Feature or improvement description**
This PR adds tower-top/ aw bearing  translational absolute velocities directed along p reference. 

- YawBrTVxp: Tower-top / yaw bearing fore-aft (translational) velocity (absolute)
- YawBrTVyp: Tower-top / yaw bearing side-to-side (translational) velocity (absolute)
- YawBrTVzp: Tower-top / yaw bearing axial (translational) velocity (absolute)

**Related issue, if one exists**
None

**Impacted areas of the software**
ElastoDyn

**Additional supporting information**

**Test results, if applicable**

No test cases can be affected because this is output is new and not currently used by any of them. 

Can you check it @andrew-platt ?

### CODE REVIEW

**Review by jjonkman — APPROVED** [review]
This looks good to me; thanks!

**Comment by andrew-platt** [comment]
@aitorplaza  Thanks for contributing!

This PR will be merged after #537 (probably later this morning).  One minor update will be required at that point for the OutlistParameters.xlsx file (that can't be merged automatically, and changes in #537).  @aitorplaza, I will make that update and post a PR to your branch.

**Comment by aitorplaza** [comment]
Thanks to you for your work. It's very useful to some of us.

**Comment by andrew-platt** [comment]
hi @aitorplaza , I created a PR to your branch at https://github.com/aitorplaza/openfast/pull/1.  This resolves the conflicts with `docs/OtherSupporting/OutListParameters.xlsx`

**Comment by aitorplaza** [comment]
@andrew-platt PR accepted

**Review by andrew-platt — APPROVED** [review]

**Pull request merged**
