### PR TITLE
Fix aeroelastic stability analysis with BeamDyn

### LINKED ISSUE #816: Bug report
**Bug description**
This is an issue that is hopefully not an issue. The fear that blades 2 and 3 in BeamDyn are not symmetric with blade 1 still circulates. I paste here some plots showing how this was clearly the case in OpenFAST v2.3.0, whereas things seem fine in v3.0.0. The simulations are run with a constant pitch of 0 deg and a constant rotor speed of 2rpm. Gravity is on, aerodynamics is off. The model is the IEA15MW from the BeamDyn branch (https://github.com/IEAWindTask37/IEA-15-240-RWT/tree/beamdyn/OpenFAST/IEA-15-240-RWT). 

TDxr
TDyr
TDzr
TipRDxr
TipRDyr
TipRDzr

**OpenFAST Version**
v2.3.0 and v3.0.0

 OpenFAST-v3.0.0
  - Compiler: Intel(R) Fortran Intel(R) 64 Compiler for applications running on Intel(R) 64,
 Compile Info:
  Version 19.1.1.217 Build 20200306
  - Architecture: 64 bit
  - Precision: double
  - OpenMP: No

If the team has special requests, I can run more cases

Thank you

### PR DESCRIPTION
**Pull request by ptrbortolotti**
This PR is ready to merge once PR #962 is merged.

Many thanks to @michaelasprague, @ebranlard, @jjonkman, and @rafmudaf for their contributions in isolating the issue.  The majority of the testing was performed by @ebranlard  and @ptrbortolotti.

**Description**
This PR fixes two issues with BeamDyn.

1. revises the method used for small angles in the linearization process.  Previously, a logarithmic mapping had been applied for small angle changes.  This resulted in discontinuities in linearization involving BeamDyn, which caused large negative damping for any blade close to a +/-180 degree azimuth (178 to 182 degree window) - see #823.
To fix this issue, the logarithmic mapping call has been removed from the `PackMotionMesh` routine in the ModMesh module, and replaced with a small angle mapping for small angles, and DCM differencing method for large angles.

2. A limit is placed on the `QFit` parameter within BeamDyn.  This now limits the maximum order of the spline fit to the keypoints to 7 instead of `order_elem`.  Without this limit, the solver within BeamDyn would go unstable in some configurations or loadings resulting in incorrect solutions for the geometry, particularly in twist.  When BeamDyn would stay stable, this could appear as differences between blade tip motions for a simplified rotor (see #816 and #818).

**Impacted areas of code**
BeamDyn primarily

A few other modules were also modified for consistency with the documentation: some modules should use small angle difference and others a large angle DCM difference.

Small angle:
- HydroDyn
- SubDyn
- ElastoDyn platform and tower
- mooring modules

Large angle DCM:
 - Blades
 - AD
 - BeamDyn

**Test Results**
No existing test cases should be affected.

**Items to complete**

- [x] Merge PR #962

**Related issues**
closes #816 #818 #823

This may partially improve issue #366

### CODE REVIEW

**Comment by ptrbortolotti** [comment]
Natural frequencies and damping ratios for the IEA 15MW RWT, release v1.1 https://github.com/IEAWindTask37/IEA-15-240-RWT/releases/tag/v1.1 without aerodynamic effects

Campbell
Campbell

**Comment by rafmudaf** [comment]
> @ebranlard are the changes in [68bb5a1](https://github.com/OpenFAST/openfast/commit/68bb5a1c1bf2ed8e8158c805fa088d22a6167b25) line endings or file permissions? Most of these changes are the entire file.

I've cleaned this up as well as the commit history here: https://github.com/rafmudaf/openfast/tree/stability_cleanup. If @ebranlard or @ptrbortolotti like it, I can force-push to the stability branch. Otherwise, @ebranlard you could change the line endings in your last commit so that the highlighted differences are the real lines of code that you changes.

**Comment by ebranlard** [comment]
Hey, It seems it was a line-ending error again. It's fine by me if we use your cleaned up version and force-push it to this branch.

**Comment by rafmudaf** [comment]
ok @ebranlard I've done it. I also have the old branch locally just in case anything is incorrect here, but I double checked that there were no unexpected differences. Could you or @ptrbortolotti get some eyes on the changes one more time?

**Pull request merged**
