### PR TITLE
Include 32 bit libraries in the MKL search

### PR DESCRIPTION
**Pull request by rafmudaf**
Fixes issue #151

### CODE REVIEW

**Comment by rafmudaf** [comment]
32 bit mkl libraries are now found for 32 bit installations. However, if both 64 bit and 32 bit libraries are installed, cmake may choose the 64 bit versions of `mkl_core` and `mkl_sequential` depending on the user's path configuration. In this case, set `MKL_SEQ_LIB` and `MKL_CORE_LIB` manually.

Additionally, documentation is included describing the process for setting the above and any other cmake flag explicitly through the command line.

**Comment by saeidfn** [comment]
Hi all,
I reached to the step "2.2.4.1. Running CMake" and I've been trying to run CMake with the syntax "cmake .. -DBUILD_SHARED_LIBS=ON", but the response I got is as follows:

E:\OpenFAST\build>cmake .. -DBUILD_SHARED_LIBS=ON
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
**-- Could NOT find MKL (missing: MKL_LIBRARIES MKL_IFACE_LIB MKL_SEQ_LIB MKL_CORE_LIB)**
-- A library with LAPACK API found.
-- Setting system file as: src/SysIVF.f90
-- Configuring done
-- Generating done
-- Build files have been written to: E:/OpenFAST/build

I already installed "Math Kernel Library" on my system, but I still don't know how to solve the error in line 2 (bold text).
Would you mind helping me with how to tackle this issue??

**Comment by rafmudaf** [comment]
Are you in the correct terminal? Depending how you've configured your Intel MKL installation, you may need to use the Intel Visual Studio Command Prompt in order for MKL to be found. You can also configure Powershell or whatever you're using to load the batch scripts in the Intel installation location.

Another thing you might try is to pass the location of the MKL libraries directly to CMake as noted in the docs: https://openfast.readthedocs.io/en/master/source/install/index.html#id3.

**Comment by saeidfn** [comment]
Dear Rafael,
what do you mean by the correct terminal??
By your explanations, I could find "Intel Visual Studio Command Prompt" but I don't know what would be the next step to find MKL.

**Comment by rafmudaf** [comment]
Try running CMake from that terminal since it should have the correct paths loaded to find the Intel libraries.

By the way, Anaconda Prompt, Command Prompt, the Intel Visual Studio Command Prompt, Powershell ... these are all different terminal applications. They all exist because they have different settings and configurations for their environment. The Anaconda Prompt has Anaconda preloaded. The Intel Visual Studio Command Prompt has Intel and Visual Studio executables and libraries in its path.

**Comment by saeidfn** [comment]
Actually I didn't understand your explanation. Initially, I ran CMake with the Command Prompt terminal at the E:OpenFAST/build directory with the syntax "cmake .. -DBUILD_SHARED_LIBS=ON" and I've got the mentioned error. By your explanation, I couldn't still understand how to find MKL Libraries.
In all of the steps, I tried to use Command Prompt and I haven't used any other options.

**Pull request merged**
