### PR TITLE
Merge of #163 (BeamDyn: Updated integration scheme for nodal load outputs)

### PR DESCRIPTION
**Pull request by ashesh2512**
**THIS PULL REQUEST IS READY TO MERGE**

This pull request although ready to merge with current dev, requires further review of the failed tests and subsequent update of gold files

**Feature or improvement description**

This pull request merges #163 (authored by @bjonkman and @andrew-platt) into the current dev after review and code modifications to align with current dev.

**Impacted areas of the software**

Beamdyn

**Additional supporting information**

**Automated test results**

A couple of tests fail, but converge to the same result as the baseline solution

Twisted beam results - 

Screen Shot 2019-03-22 at 3 12 35 PM

Curved beam results -

Screen Shot 2019-03-22 at 3 34 45 PM

### CODE REVIEW

**Comment by ashesh2512** [comment]
@andrew-platt Could you please look through these changes? A couple of tests failed. Is this an artifact of the modified computation of ` m%FirstNodeReactionLclForceMoment`  ?

**Comment by andrew-platt** [comment]
Hmm... these results don't look right.  I'll try to take a look in more detail later in the week.

**Comment by ashesh2512** [comment]
I further wanted to add `Fx` and `Mx` plots along the beam axis for the standalone 5MW dynamics test case. The plots below show a clear improvement in load profiles.

Screen Shot 2019-03-26 at 1 04 18 PM

the closeup - 

Screen Shot 2019-03-26 at 1 04 34 PM

**Comment by andrew-platt** [comment]
This looks correct to me.  Do the Fy and My terms show similar trends as well?

**Comment by ashesh2512** [comment]
@andrew-platt I plotted the Fy and My and the My profile with the current approach shows load reversals near the blade tip (see close-up of red plot)

Entire blade - 

Screen Shot 2019-03-26 at 9 05 29 PM

Zoomed in -

Screen Shot 2019-03-26 at 9 05 54 PM

**Comment by ashesh2512** [comment]
After some discussion with @andrew-platt, since the load reversal vanishes with increasing the refinement, there is likely a slight under-sampling near the tip with where the trapezoidal quadrature points are defined.  So it is suspected that this might be a small artifact of the spectral method resulting in a difference 4 orders of magnitude smaller than the largest load, and not an issue with the load integration scheme.

**Comment by andrew-platt** [comment]
Since this PR supercedes the PR #163, can we close that one?

**Pull request merged**
