### PR TITLE
Adds performance optimization to NWTC Lib and BeamDyn

### PR DESCRIPTION
**Pull request by hlong0806**
For beamdyn and modmesh changes: Some values are calculated repeatedly. The straight forward idea is to calculate it and store in a temporary variable and use it later.
For nwtc_num change: calculate the 3X3 matrix directly instead of doing matrix multiply.

**This pull request is currently being modified.**

### CODE REVIEW

**Comment by bjonkman** [comment]
@rafmudaf: These optimizations in BeamDyn are covered in my EE-BeamDyn-OpenFAST-dev branch that you said you were going to review and merge (I calculate and store these constant values at initialization). There will be conflicts later if you accept the BD changes.

**Comment by rafmudaf** [comment]
@bjonkman Thank you for pointing out this merge conflict. This pull request is still under development, but I'll work on validating your changes in the meantime.

**Comment by michaelasprague** [comment]
@sinolonghai (@sayerhs ) can we close this given recent pull request (https://github.com/OpenFAST/openfast/pull/114) and current Intel PCC work?

**Comment by sayerhs** [comment]
@michaelasprague Yes, we can close this and submit a pull request after our IPCC work this year.

**Pull request closed without merging**
