### PR TITLE
Release v2.2.0

### LINKED ISSUE #118: Improve User-Specified Wave-Kinematics File Formatting Requirements for WaveMod = 6
The data format of the various user-specified wave-kinematics input files (.Elev, .Vxi, .Vyi, .Vzi, .Axi, .Ayi, .Azi, and .DynP) used with the WaveMod = 6 option in HydroDyn are very finicky, with very specific requirements regarding data format, white space, etc.  This has caused many users trouble.  HydroDyn should be made more robust so that the data format requirements are more user-friendly.  More information can be found in the following forum topic: https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=1690.

### LINKED ISSUE #246: Small Error Regarding WaveDirMod
HydroDyn input parameter WaveDirMod is supposed to be used only when WaveMod=2, 3, or 4.  However, the logic in routine HydroDyn_Input.f90/HydroDynInput_ProcessInitData() forces WaveMod to equal 0 if WaveDirMod == 1 and WaveMod <> 2, 3, or 4.  Instead of setting WaveMod = 0, WaveMultiDir should be set to .FALSE. in this case.

This issue was reported in the following topic on the forum: https://wind.nrel.gov/forum/wind/viewtopic.php?f=4&t=2213.

### PR DESCRIPTION
**Pull request by rafmudaf**
Complete this sentence
**THIS PULL REQUEST IS READY TO MERGE**

**Feature or improvement description**
This pull request merges `dev` into `master` for a tagged release, `v2.2.0`. See below for the proposed change log.

**Related issue, if one exists**
None

**Impacted areas of the software**
See the change log.

**Additional supporting information**
Its been a long time! In an effort to improve internal processes, I suggest going forward with releasing OpenFAST v2.2.0 as there are major differences between the `master` and `dev` branches, at the moment. As there is ongoing work in existing pull requests and upcoming pull requests, I anticipate another minor version release in the near future.

**Automated test results**
The baseline results have changed since the last release and have been maintained up to date on `dev`.

---

**Proposed change log**

General
- Simulink interface updated and improved
- OpenFAST Registry made optional and all module-types files added to version control (https://github.com/OpenFAST/openfast/pull/337)
- Consolidated `modules-ext` and `modules-local` into `modules` and added module README's
- Solve Option 2 Performance enhancements
    - Parts of the SolveOption2 algorithm have been moved to the the AdvanceStates routine so that BeamDyn, InflowWInd, AeroDyn, and ServoDyn use calculated inputs instead of extrapolations for inputs at t+dt. This change allows BeamDyn to use calculate rotations and AeroDyn/DBEMT to use calculated velocities, which otherwise would require a correction step. In DBEMT this was a problem with high turbulence and low wind speeds.

C++ API
- Bug fix when building with MPI
- Fix out-of-bounds memory access in C++ API

BeamDyn
- Updated integration scheme for nodal load outputs (#265) 
   --> NOTE: further improvements are in progress for this feature.

HydroDyn
- WaveMode set to 0 instead of WaveDirMod (Fixes #246)
- Allow number of Morison number to be 0 (see #79)
- Add safety on number of lines and number of fields per line when WaveMode=6 (Should Fix #118)
- Always initialize WaveElevSeries if WaveElevXY is set
- Update array bounds in calculation in Morrison

VTK Visualization
- Zero padding of VTK names, and log10 of zero (see #250)

Build system
- Sync the git versions for windows and linux builds
- Add a Version module to improve version handling
- Improve support for CygWin builds

Documentation
- Add API change log
- Major structural changes, improvements, and additions to content

InflowWind
- Fix InflowWind index for invalid channels

AeroDyn
- Improve performance in BEMT error handling
- Fix incorrect node number in linearization error messages

SubDyn
- Major cleanup of source code

ElastDyn
- Fix issue with OP if blade pitch isn't equal on all blades

The following modules have minor bug fixes not listed above:
- AeroDyn
- AeroDyn14
- HydroDyn
- InflowWind
- SubDyn
- Turbsim

### CODE REVIEW

**Comment by rafmudaf** [comment]
@andrew-platt @ebranlard @ashesh2512 I've requested your review here mostly on the change log. Please let me know if I've missed anything.

**Comment by andrew-platt** [comment]
I added a note on the registry dependency.  @rafmudaf, should more be said regarding this?

**Comment by rafmudaf** [comment]
@andrew-platt I had a note on that in the general section:
```
OpenFAST Registry made optional and all module-types files added to version control
```

**Comment by rafmudaf** [comment]
I'll add the PR link to that comment so people can find further information

**Pull request merged**
