### PR TITLE
Configure runtime path linking when using shared libraries

### PR DESCRIPTION
**Pull request by rafmudaf**
**Feature or improvement description**
This pull request configures the RPATH setting in CMake to configure where executables look for shared libraries when compiled with the BUILD_SHARED_LIBS setting enabled.

**Related issue, if one exists**
https://github.com/OpenFAST/openfast/issues/430
https://github.com/OpenFAST/openfast/issues/441

**Impacted areas of the software**
Any targets compiled with shared libraries

### CODE REVIEW

**Review by sayerhs — APPROVED** [review]

**Comment by andrew-platt** [comment]
Does this allow for dylibs to be ported between systems?

**Comment by rafmudaf** [comment]
The libraries would still have to be available in the destination-system's `rpath`, but otherwise yes. This removes the hard-coded path to dynamically linked libraries in executables.

**Comment by andrew-platt** [comment]
I'll check to see if this fixes the issues with the Simulink builds

**Comment by andrew-platt** [comment]
this doesn't seem to work out of the box for mac:

```
Caused by:
    Error using Run_OpenLoop (line 12)
    Invalid MEX-file '/Users/aplatt/software-development/GitHub/openfast-2/install/lib/FAST_SFunc.mexmaci64':
    dlopen(/Users/aplatt/software-development/GitHub/openfast-2/install/lib/FAST_SFunc.mexmaci64, 6): Library not loaded: @rpath/libopenfastlib.dylib
      Referenced from: /Users/aplatt/software-development/GitHub/openfast-2/install/lib/FAST_SFunc.mexmaci64
      Reason: image not found
```

**Pull request merged**
