### PR TITLE
minor bug fix

### PR DESCRIPTION
**Pull request by lapadron**
**Complete this sentence**
THIS PULL REQUEST IS READY TO MERGE

**Feature or improvement description**
Minor bug fix in SubDyn_Driver. The first dimension of array SDin was begin accessed from index 0 and the do loop had one step too many. 

**Impacted areas of the software**
SubDyn_Driver

### CODE REVIEW

**Comment by andrew-platt** [comment]
Can we change this to a PR to the `dev` branch instead of `master`?

**Comment by rafmudaf** [comment]
Well actually it looks like @lapadron left off the commit making the change. This pull request only contains the commits already on `dev`.

**Comment by andrew-platt** [comment]
@lapadron did you push your update to your branch on GitHub?

**Comment by lapadron** [comment]
Sorry. I hadn't done the 'git add'. Now I did it and repeated steps 5 and 6. Do I need to do a new pull request now?

**Comment by andrew-platt** [comment]
`n` should probably start at 0 so that line 241 gives `T=0`.

**Comment by rafmudaf** [comment]
Ah good point @andrew-platt

**Pull request merged**
