### PR TITLE
Add API changelog to the docs

### PR DESCRIPTION
**Pull request by rafmudaf**
Complete this sentence
**THIS PULL REQUEST IS READY TO MERGE**

**Feature or improvement description**
Adds an API changelog to the readthedocs documentation.

A clear and concise description of the new code.
The included updates exist only in the documentation. A new page is added to the user section which lists the changes for each new version of OpenFAST.

**Related issue, if one exists**
None

**Impacted areas of the software**
Documentation

**Additional supporting information**
None

**Automated test results**
Not applicable. A live version of this documentation is available at: https://raf-openfast.readthedocs.io/en/docs-changelog/source/user/api_change.html

### CODE REVIEW

**Comment by rafmudaf** [comment]
@ebranlard could you also review this pull request?

**Comment by ebranlard** [comment]
This looks good to me, I've done some small edits. In the future, we can try to have a diff of the files side by side, but that might be tricky to do in rst.

**Comment by rafmudaf** [comment]
Nice, thanks for making those changes. I agree, a side by side comparison would be nice. I tried a table with two major columns but since the current readthedocs theme has a narrow area of the page for content a lot of the table was cut off.

**Comment by jjonkman** [comment]
Thanks, @rafmudaf; this is a much needed improvement to the documentation!

Just a couple comments:
- In OpenFAST v0.1, option 2 was added for CompSub on line 18 of the OpenFAST primary input file (the line was not added or deleted, but was changed) e.g. "0 CompSub - Compute sub-structural dynamics (switch) {0=None; 1=SubDyn; 2=External Platform MCKF}".  I suggest adding this in section, "FAST v8.16 to OpenFAST v1.0.0".
- I suggest removing the section "FAST v7 to FAST v8".  This section is far from complete and there are statements that are misleading (e.g. ElastoDyn did not exist in FAST v7; HydroDyn did exist, but is not stated; several other inputs are handled differently).  Instead, I would refer users to the old FAST v8 ReadMe file for the full documentation on the changes, including the MATLAB conversion scripts: https://wind.nrel.gov/nwtc/docs/README_FAST8.pdf.

**Comment by rafmudaf** [comment]
@jjonkman thanks for looking over this. I've added your suggestions.

**Pull request merged**
