### PR TITLE
Fix library settings for OpenFAST C++ API libraries

### LINKED ISSUE #208: OpenFAST build errors on macOS missing MPI symbols when building as shared library
I'm seeing these errors during the 99% linking phase when building on macOS with OpenMPI 3.1.3:
```
Undefined symbols for architecture x86_64:
  "_MPI_Allreduce", referenced from:
      fast::OpenFAST::fillScInputsGlob()     in OpenFAST.cpp.o
  "_MPI_Comm_create", referenced from:
      fast::OpenFAST::allocateMemory()     in OpenFAST.cpp.o
  "_MPI_Comm_free", referenced from:
      fast::OpenFAST::end()    in OpenFAST.cpp.o
  "_MPI_Comm_group", referenced from:
      fast::OpenFAST::setInputs(fast::fastInputs const&) in OpenFAST.cpp.o
  "_MPI_Comm_rank", referenced from:
      fast::OpenFAST::allocateMemory()     in OpenFAST.cpp.o
      fast::OpenFAST::setInputs(fast::fastInputs const&) in OpenFAST.cpp.o
  "_MPI_Comm_size", referenced from:
      fast::OpenFAST::allocateTurbinesToProcsSimple()     in OpenFAST.cpp.o
  "_MPI_Group_free", referenced from:
      fast::OpenFAST::end()    in OpenFAST.cpp.o
  "_MPI_Group_incl", referenced from:
      fast::OpenFAST::allocateMemory()     in OpenFAST.cpp.o
  "_ompi_mpi_comm_null", referenced from:
      fast::OpenFAST::end()    in OpenFAST.cpp.o
      fast::OpenFAST::fillScInputsGlob()     in OpenFAST.cpp.o
      fast::OpenFAST::allocateMemory()     in OpenFAST.cpp.o
  "_ompi_mpi_double", referenced from:
      fast::OpenFAST::fillScInputsGlob()     in OpenFAST.cpp.o
  "_ompi_mpi_op_sum", referenced from:
      fast::OpenFAST::fillScInputsGlob()     in OpenFAST.cpp.o
ld: symbol(s) not found for architecture x86_64
```
I will update this when I test whether or not OpenMPI 1.10.4 still works, which was previously known to work.

### PR DESCRIPTION
**Pull request by sayerhs**
Fixes #208

### CODE REVIEW

**Comment by sayerhs** [comment]
This pull request is ready to merge. Fixes compilation on OSX as reported by #208 and doesn't introduce any other code changes to impact any regression tests.

**Comment by rafmudaf** [comment]
@sayerhs We merge pull requests into `dev` and then merge to master only on a release. Are you suggesting this merge into master as v2.1.1?

**Comment by jrood-nrel** [comment]
Can we just merge into `dev` today? That's what I use.

**Comment by rafmudaf** [comment]
@jrood-nrel I've merged #242 into dev and closed the corresponding issue. Please let me know if this bug isn't fixed, however.

**Pull request closed without merging**
