### PR TITLE
Add a “version” module to remove git dependency

### PR DESCRIPTION
**Pull request by rafmudaf**
**Complete this sentence**
THIS PULL REQUEST IS READY TO MERGE

**Feature or improvement description**
This pull request changes the versioning system as it was initially implemented in CMake. This does not affect the build for Windows with Visual Studio.

The existing implementation inserts the git hash (AKA the version) into the source code through a compiler flag and preprocessor directive in NWTC_IO. Therefore, anytime the git status changes the compile command also changes so everything has to be recompiled.

This pull request improves the build system
1. Moving the git status checking to a standalone module
2. Moving the compiler flag from the main CMakeLists to the new module CMakeLists

These changes mean that the compile command for the other modules does not change with the git commit and only the lightweight Version module needs to be recompiled. The driver programs which use this module are relinked during compile time.

**Related issue, if one exists**
https://github.com/OpenFAST/openfast/issues/267

**Impacted areas of the software**
The build system through CMake

**Additional supporting information**
This is important when dealing with multiple branches as the git status changes frequently. Also, it will enable improved performance in the automated testing.

**Test results, if applicable**
Only the existing TravisCI tests are necessary.

### CODE REVIEW

**Comment by rafmudaf** [comment]
@bjonkman thank you for creating issue #267. I think this pull request addresses it as you've described. Could you please take a look?

**Comment by bjonkman** [comment]
I just briefly glanced through the changed files. Are you sure the Windows Visual Studio solution files will actually successfully build with these changes? I would be very surprised if they work without adding the new `VersionInfo.f90` file to their list of source files.

**Comment by bjonkman** [comment]
@rafmudaf I just made a pull request to your branch to address the changes that need to happen in the Visual Studio builds.

**Comment by rafmudaf** [comment]
Thank you very much @bjonkman. After that bug fix, @ebranlard do you have any comments?

**Comment by rafmudaf** [comment]
By the way, the failed TravisCI check is due to the expired intel license. In another pull request, I'll remove that test from the Travis setup until we get a better solution.

**Comment by ebranlard** [comment]
Everything looks good to me!

**Pull request merged**
