### PR TITLE
hd: add NBodyMod regression tests

### PR DESCRIPTION
**Pull request by andrew-platt**
This is ready for merging.

**Feature or improvement description**
Flexible platform capability was added to OpenFAST v2.6.0 in HydroDyn.  This included a new flag `NBodyMod` with three methods of handling multiple potential flow (WAMIT) bodies.  No test cases were added at that time.

This was a set of test cases developed by @mattEhall some time ago.

**Related issue, if one exists**
#1480 fixed a bug in `NBodyMod = 1`

**Impacted areas of the software**
Testing of HydroDyn `NBodyMod` options only

**Test results, if applicable**
New test cases have been added.  These are based on the OC4Semi test case, but treat the floating platform as 4 separate bodies (center column, and 3 corner columns):

- `NBodyMod1` -- a single set  of WAMIT files includes coupling terms between each body (PtfmRefxt/yt/zt/ztRot should match XBODY(1)/(2)/(3)/(4) in WAMIT and NBody should match NBODY in WAMIT)
- `NBodyMod2` -- 4 separate WAMIT bodies neglecting couplings between each body and NBODY=1 with XBODY=0 in WAMIT (PtfmRefxt/yt/zt/ztRot may differ from XBODY(1)/(2)/(3)/(4) in WAMIT)
- `NBodyMod3` -- 4 separate WAMIT bodies neglecting couplings between each body and NBODY=1 with XBODY=/0 in WAMIT (PtfmRefxt/yt/zt/ztRot should match XBODY(1)/(2)/(3)/(4) in WAMIT)

### CODE REVIEW

**Comment by andrew-platt** [comment]
@luwang00, could you review this?

**Review by jjonkman — COMMENTED** [review]
Overall, these tests make sense to me, but I haven't confirmed all details.  Have you compared the results of the three tests against each other?  Hopefully the results are quite consistent between the three tests?

**Comment by luwang00** [comment]
I've gone through the run files briefly. This is probably not critical for verification, but it makes more sense physically to set PropPot to TRUE for Member 1, the central column, which is already modeled as a potential-flow body.

**Comment by andrew-platt** [comment]
The surge, heave, and pitching moments all agree relatively well between the three models (the sway, roll, and yaw moments are very small and show differences).

Lu also ran some quick tests that showed relatively close agreement between the models.

**Review by jjonkman — APPROVED** [review]
Thanks for answering my question.  I approve this PR, assuming you address @luwang00's comment.

**Pull request merged**
