### PR TITLE
bugfix: Increasing robustness for interpolation of Tower properties in the OpenFOAM module

### PR DESCRIPTION
**Pull request by gantech**

### CODE REVIEW

**Comment by gantech** [comment]
@rafaelmudafort What's the policy on pull requests. Do I show that all tests pass?

**Comment by rafaelmudafort** [comment]
@gantech yes, including the print out of all tests passing is good enough

**Comment by rafaelmudafort** [comment]
@gantech you're good to go wrt testing. 
```
Test project /Users/rmudafor/Desktop/OpenFAST/build
      Start  1: AWT_YFix_WSt
 1/31 Test  #1: AWT_YFix_WSt .............................   Passed   21.11 sec
      Start  2: AWT_WSt_StartUp_HighSpShutDown
 2/31 Test  #2: AWT_WSt_StartUp_HighSpShutDown ...........   Passed   27.09 sec
      Start  3: AWT_YFree_WSt
 3/31 Test  #3: AWT_YFree_WSt ............................   Passed   32.91 sec
      Start  4: AWT_YFree_WTurb
 4/31 Test  #4: AWT_YFree_WTurb ..........................   Passed  109.24 sec
      Start  5: AWT_WSt_StartUpShutDown
 5/31 Test  #5: AWT_WSt_StartUpShutDown ..................   Passed   40.59 sec
      Start  6: AOC_WSt
 6/31 Test  #6: AOC_WSt ..................................   Passed   21.75 sec
      Start  7: AOC_YFree_WTurb
 7/31 Test  #7: AOC_YFree_WTurb ..........................   Passed  118.41 sec
      Start  8: AOC_YFix_WSt
 8/31 Test  #8: AOC_YFix_WSt .............................   Passed   36.67 sec
      Start  9: UAE_Dnwind_YRamp_WSt
 9/31 Test  #9: UAE_Dnwind_YRamp_WSt .....................   Passed   97.72 sec
      Start 10: UAE_Upwind_Rigid_WRamp_PwrCurve
10/31 Test #10: UAE_Upwind_Rigid_WRamp_PwrCurve ..........   Passed   61.77 sec
      Start 11: WP_VSP_WTurb_PitchFail
11/31 Test #11: WP_VSP_WTurb_PitchFail ...................   Passed   27.73 sec
      Start 12: WP_VSP_ECD
12/31 Test #12: WP_VSP_ECD ...............................   Passed   30.32 sec
      Start 13: WP_VSP_WTurb
13/31 Test #13: WP_VSP_WTurb .............................   Passed   83.17 sec
      Start 14: WP_Stationary_Linear
14/31 Test #14: WP_Stationary_Linear .....................   Passed    1.37 sec
      Start 15: SWRT_YFree_VS_EDG01
15/31 Test #15: SWRT_YFree_VS_EDG01 ......................   Passed  203.53 sec
      Start 16: SWRT_YFree_VS_EDC01
16/31 Test #16: SWRT_YFree_VS_EDC01 ......................   Passed  121.55 sec
      Start 17: SWRT_YFree_VS_WTurb
17/31 Test #17: SWRT_YFree_VS_WTurb ......................   Passed  485.38 sec
      Start 18: 5MW_Land_DLL_WTurb
18/31 Test #18: 5MW_Land_DLL_WTurb .......................   Passed  138.76 sec
      Start 19: 5MW_OC3Mnpl_DLL_WTurb_WavesIrr
19/31 Test #19: 5MW_OC3Mnpl_DLL_WTurb_WavesIrr ...........   Passed  365.36 sec
      Start 20: 5MW_OC3Trpd_DLL_WSt_WavesReg
20/31 Test #20: 5MW_OC3Trpd_DLL_WSt_WavesReg .............   Passed  1315.28 sec
      Start 21: 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth
21/31 Test #21: 5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth ...   Passed  3030.03 sec
      Start 22: 5MW_ITIBarge_DLL_WTurb_WavesIrr
22/31 Test #22: 5MW_ITIBarge_DLL_WTurb_WavesIrr ..........   Passed   75.64 sec
      Start 23: 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti
23/31 Test #23: 5MW_TLP_DLL_WTurb_WavesIrr_WavesMulti ....   Passed  128.63 sec
      Start 24: 5MW_OC3Spar_DLL_WTurb_WavesIrr
24/31 Test #24: 5MW_OC3Spar_DLL_WTurb_WavesIrr ...........   Passed  116.75 sec
      Start 25: 5MW_OC4Semi_WSt_WavesWN
25/31 Test #25: 5MW_OC4Semi_WSt_WavesWN ..................   Passed  238.68 sec
      Start 26: 5MW_Land_BD_DLL_WTurb
26/31 Test #26: 5MW_Land_BD_DLL_WTurb ....................   Passed  556.44 sec
      Start 27: static_cantilever_beam
27/31 Test #27: static_cantilever_beam ...................   Passed    0.68 sec
      Start 28: isotropic_rollup
28/31 Test #28: isotropic_rollup .........................   Passed    0.62 sec
      Start 29: curved_beam
29/31 Test #29: curved_beam ..............................   Passed    0.68 sec
      Start 30: 5MW_dynamic
30/31 Test #30: 5MW_dynamic ..............................   Passed   51.30 sec
      Start 31: beamdyn_utest
31/31 Test #31: beamdyn_utest ............................   Passed    0.06 sec

100% tests passed, 0 tests failed out of 31

Label Time Summary:
aerodyn14    = 838.56 sec (7 tests)
aerodyn15    = 6647.29 sec (19 tests)
beamdyn      = 609.72 sec (5 tests)
dynamic      =  51.30 sec (1 test)
elastodyn    = 6929.42 sec (25 tests)
hydrodyn     = 5270.37 sec (7 tests)
map          = 321.01 sec (3 tests)
moordyn      = 238.68 sec (1 test)
openfast     = 7485.86 sec (26 tests)
servodyn     = 7484.49 sec (25 tests)
static       =   1.99 sec (3 tests)
subdyn       = 4710.67 sec (3 tests)

Total Test time (real) = 7539.26 sec
```

**Comment by gantech** [comment]
Thanks @rafaelmudafort. I'll merge this now.

**Pull request merged**
