### PR TITLE
Build system fixes on linux

### PR DESCRIPTION
**Pull request by reos-rcrozier**
**Feature or improvement description**
Fixes issues with installing and building on Linux, especially simulink interface

**Impacted areas of the software**
Build system

**Additional supporting information**
Installing the C++ interface failed on linux due to a typo in the file named SC.h in CMakeLists.txt I have changed it from SC.H -> SC.h
This problem probably doesn't show up on windows as it's file system is case insensitive

I also fixed an issued with building the simulink S-Function on linux. mex on linux does not use COMPFLAGS, you must use CFLAGS or CXXFLAGS, also the -MT option does something very different in gcc than visual studio C++

### CODE REVIEW

**Comment by rafmudaf** [comment]
@bjonkman could you check out these changes to the Simulink API build system?

**Comment by reos-rcrozier** [comment]
all tests passing on this branch for me see results [here](https://github.com/REOptimize-Systems/openfast/actions/runs/3962923142)

Can we consider merging please

**Review by andrew-platt — APPROVED** [review]

**Comment by andrew-platt** [comment]
@reos-rcrozier, I'll merge this as soon as GH actions completes.  These changes should make no difference to GH since it is just in the create_sfunc.m that isn't run in testing.

I'm letting the tests run mostly to see if I can learn anything about why GH actions is failing for us.

**Comment by reos-rcrozier** [comment]
OK, thanks!

**Pull request merged**
