### PR TITLE
Reg-test scripts modification to help avoid race condition and cleanup of caselist

### PR DESCRIPTION
**Pull request by andrew-platt**
This PR is ready to be merged

**Feature or improvement description**
As discussed in PR #1199, there is a frequent issue with race conditions when copying test case inputs over to the regression testing location.  This is caused by the `shutil.copytree` command that errors out if there are pre-existing files.  To get around this issue, the `rtl.copyTree` command is now used.  

Additionally, three test cases are dropped from the python interface testing and HydroDyn module testing.  These cases are equivalent to ones that had been dropped from main OpenFAST test case list as they do not agree sufficiently between platforms for the new testing methodology (likely due to numerical issues in HydroDyn).  These cases include:
- Python interface test:
    - `5MW_ITIBarge_DLL_WTurb_WavesIrr_py`
- HydroDyn module tests:
    - `hd_5MW_ITIBarge_DLL_WTurb_WavesIrr`
    - `hd_5MW_OC4Jckt_DLL_WTurb_WavesIrr_MGrowth`

**Related issue, if one exists**
See comment https://github.com/OpenFAST/openfast/pull/1199#issuecomment-1233158938 and following discussion in PR #1199 for context on the `rtl.copyTree`.
The dropped cases should have been dropped with PR #1217.

**Impacted areas of the software**
This only affects the running of test cases.

**Test results, if applicable**
See above.

### CODE REVIEW

**Comment by andrew-platt** [comment]
This may partially fix an issue in testing for PR #1086.

**Comment by deslaughter** [comment]
The `rtest-interfaces` action failed because the `5MW_Land_DLL_WTurb_cpp` test couldn't find its `yaml` input file. I think that `.yaml` was one of the file types in the `excludeExt` list which was added to the Python files. Changing `.yaml` to `.sum.yaml` in the `excludeExt` list should fix the issue by excluding the regression test reference files, but still allowing the input file. However, this change would require modifying `rtestlib.py` to something other than `os.path.splitext` to get the extension. It may be better to remove `.yaml` from `excludeExt` in `executeOpenfastCppRegressionCase.py`.

While these changes will reduce the chances of the script failing due to simultaneous tests writing to the same file, they won't prevent it, as discussed in PR #1199.

**Comment by andrew-platt** [comment]
Thanks for looking at this!  I agree this is not going to completely solve the race condition.

**Review by deslaughter — APPROVED** [review]
Changes look good and all tests are passing.

**Pull request merged**
