### PR TITLE
Update to latest HDF5

### PR DESCRIPTION
**Pull request by tonyinme**
The wget command does not work for version 1.8.19.
The version on the web is 1.8.20.
The script has been updated to do this.

### CODE REVIEW

**Comment by tonyinme** [comment]
Hey Ganesh,

Yes, I agree.
I have always had the same issue with hdf5, there is no clean way of
getting the source code (like git clone).
If that link you are suggesting works, then go ahead and change it to that.
The scripts in share are very good, and they should be the go-to for
compilation.

**Comment by sayerhs** [comment]
@gantech It would be good if you set the same version for OpenFAST as Trilinos/Nalu so that there are no conflicts when we attempt to link to Nalu.

**Comment by rafmudaf** [comment]
@gantech is this pull request good to go or do you need to address @sayerhs suggestion above?

**Comment by gantech** [comment]
As soon as @tonyinme accepts this pull request https://github.com/tonyinme/openfast/pull/1, this will be ready to go.

**Comment by tonyinme** [comment]
Looks good!

**Pull request merged**
